/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.pgatzka.docker;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class DockerPlugin implements Plugin<Project> {

    public void apply(Project project) {
        project.getTasks().register("greeting", task -> task.doLast(s -> System.out.println("Hello from plugin 'org.example.greeting'")));
    }

}
